apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app }}-service"
  namespace: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}